### ISSUE TITLE
cdk s3 trigger for lambda functions

### ISSUE THREAD

**Issue by HusainAdel** [bahrain-uob/eco-guard-challenge#101]

**Comment by yomnak** [comment]
-  https://github.com/aws/aws-cdk/tree/v2.137.0/packages/aws-cdk-lib/triggers
- https://github.com/aws/aws-cdk/tree/v2.137.0/packages/aws-cdk-lib/aws-s3

**Comment by HusainAdel** [comment]
@maramesk @cerashdan having an issue with the S3 trigger through cdk/sst using the provided ^ resources. They call for calling the trigger after creating the lambda function through cdk rather than sst and use the variable name- we cant do the same when creating it in sst and is giving us errors. Please advise.

**Comment by maramesk** [comment]
@HusainAdel If I understood you issue correctly, you can trigger lambda from S3 events with SST by importing your lambda in your S3 bucket stack and then using it as notification under bucket creation, you can find the directions here : https://docs.sst.dev/constructs/Bucket 

Heres an example of how previous sem students have used it as well:
<img width="628" alt="Screenshot 2024-05-21 at 9 29 13 AM" src="https://github.com/bahrain-uob/eco-guard-challenge/assets/100120242/3b6f124e-db93-403d-acff-cd1e2b17c947">

**Comment by HusainAdel** [comment]
thank you that is helpful; We have used this documentation, and we see where we went wrong. This issue has been moved to #125 & #124
