### ISSUE TITLE
US1-Database storage system to store results and display them in the dashboard

### ISSUE THREAD

**Issue by Dalmajed** [bahrain-uob/eco-guard-challenge#23]
- Decide whether separate tables for each violation is necessary or if one table for all violations will suffice

**Comment by Dalmajed** [comment]
I can't push my code(2 tables created) with mock data until the actual data is ready to be retreived
somebody help me please  @maramesk

**Comment by HusainAdel** [comment]
rds was created and will be linked to frontend through api
