### ISSUE TITLE
Automatic License Plate Recognition Implementation

### ISSUE THREAD

**Issue by mohammedalsaeed-uob** [bahrain-uob/eco-guard-challenge#51]
- Decide on implementation (https://github.com/computervisioneng/real-time-number-plate-recognition-anpr) or (https://github.com/licesonw/anpr-sagemaker-custom?tab=readme-ov-file#automated-number-plate-recognition-with-amazon-sagemaker)
- Implement Chosen Solution

**Comment by mohammedalsaeed-uob** [comment]
https://github.com/Muhammad-Zeerak-Khan/Automatic-License-Plate-Recognition-using-YOLOv8

**Comment by mohammedalsaeed-uob** [comment]
Brainstormed a few tasks:
1. Add function to delete snapshots captured by Unregistered Cars Consumer
2. Add function to retain snapshots captured by Yellow Lane Violation Consumer
3. Create Folders for Separate Violations in S3 Violation Bucket
4. Create DynamoDB table for Yellow Lane Violation License Plate Storage

**Comment by mohammedalsaeed-uob** [comment]
We successfully developed Consumer 1. 
- It takes the stream as input from Kinesis Video Streams. 
- A car and license plate detector model on the captures images of license plates and saves them to S3
- A lambda function takes the image from S3 and runs it against Amazon Textract to get the license plate number
- The same lambda function stores the extracted license plate number into a Dynamo DB table.

**Comment by mohammedalsaeed-uob** [comment]
Inquiry @maramesk @cerashdan 

The model is alright, but it's not the most accurate: It sometimes captures extra characters. 
We have the option of training it on Bahraini cars. Our question is: Is that a priority? There are two key points to consider here

- This model is reused throughout all our consumers to detect cars and their license plates.
- We're not sure if it's what we should focus our efforts on right now. 

Should we focus some of our efforts on training the model now? Or should we come back to it at a later time when we've made more the other consumers (for the other violations)?

**Comment by maramesk** [comment]
@mohammedalsaeed-uob The returning students from the Amakin Challenge (currently working in BQA) have implemented accurate plate detection on Bahraini plate numbers, reach out to them to check their approach. They did not have to train their own model on Bahraini plates and I don't think its feasible for you to do so either.

**Comment by cerashdan** [comment]
Adding few more pointers to guide you: 

1. When solving computer vision problems, think about your scene and try to eliminate unnecessary information. If you have a scene with many cars, try the following: 

- Detect cars in the scene
- Save the car bounding box in an array (n * m * k numpy array where n is the number of cars and m * k is the resized cropped car)
- Filter out the interest region, Bahraini plates have a red flag, dark edge and a white background. Find methods that can detect this area.
- Once you find this area, crop only the license plate. then run your ML model to detect the digits. 

**Using textract for every frame is unpractical as you are processing a video**. This problem could easily be solved using ML approaches running on the consumer itself.

**Comment by cerashdan** [comment]
Automatic License/Number Plate Recognition (ANPR/ALPR) is a solved problem in Machine Learning, have a look at: 

https://pyimagesearch.com/2020/09/21/opencv-automatic-license-number-plate-recognition-anpr-with-python/

More specifically this section: 
Lines 30 and 31 perform a [blackhat morphological operation](https://docs.opencv.org/trunk/d9/d61/tutorial_py_morphological_ops.html) to reveal dark characters (letters, digits, and symbols) against light backgrounds (the license plate itself). As you can see, our kernel has a rectangular shape of 13 pixels wide x 5 pixels tall, which corresponds to the shape of a typical international license plate

![Screenshot 2024-05-05 133842](https://github.com/bahrain-uob/eco-guard-challenge/assets/54531553/62e6c034-4249-451b-97d4-4ba8a4c9c47f)

**Comment by mohammedalsaeed-uob** [comment]
@cerashdan Thank you for sharing these invaluable pointers and resources. I would like to point out that we are **not** using Textract on every frame, so no need to worry about that. After adjusting the code, it generally works much better now. Thank you once again.

**Comment by mohammedalsaeed-uob** [comment]
Currently migrating our functions and code to SST, then we can close this issue.

**Comment by HusainAdel** [comment]
#87 and #88 branches for dyanamo, s3, lambda functions
