### ISSUE TITLE
Modify Lambda Function for Unregistered Car Case

### ISSUE THREAD

**Issue by mohammedalsaeed-uob** [bahrain-uob/eco-guard-challenge#53]
- Case 2: Modify Lambda function to insert unregistered car number into Unregistered Car Table of the Violation Database (RDS)

**Comment by yomnak** [comment]
-modification: if the car is not registered then insert it into violated-car table , otherwise, delete the image from the s3 bucket.

**Comment by mohammedalsaeed-uob** [comment]
@yomnak wrote the code and logic for what should happen when an entry of a new license plate comes in. I then picked up the work and continued in a different issue (see #81).
