### ISSUE TITLE
Failed to build DBStack

### ISSUE THREAD

**Issue by Dalmajed** [bahrain-uob/eco-guard-challenge#63]
@cerashdan @maramesk We are facing a problem in building the DBStack

![Image](https://github.com/bahrain-uob/eco-guard-challenge/assets/133596702/dfb7c3d0-4a52-43c1-844c-ff5ab07ac372)

**Comment by mohammedalsaeed-uob** [comment]
[This link](https://stackoverflow.com/questions/58192747/aws-aurora-serverless-communication-link-failure) suggests that the error might be "expected," regarding the Bad Communications Link. Apparently, running the command 3-4 times may help the issue.

Other sources suggest that there's a problem with the connection to your SQL database, so maybe we could double check that. 

@Dalmajed

**Comment by cerashdan** [comment]
@Dalmajed can you try what Mohammed suggested? I noticed a team has run the code multiple time and it worked.
