### ISSUE TITLE
modify review page css

### ISSUE THREAD

**Issue by yomnak** [bahrain-uob/eco-guard-challenge#66]

**Comment by yomnak** [comment]
modified css in review page 
installed  : 
pnpm install @fortawesome/fontawesome-free 
pnpm install --save react-icons

**Comment by yomnak** [comment]
checks error "failed to run npm ci"


![Image](https://github.com/bahrain-uob/eco-guard-challenge/assets/94840167/91c99ca3-c0c1-4228-b824-e36fc1fefe09)


@cerashdan @maramesk

**Comment by yomnak** [comment]
I've updated my pnpm and then pushed the changes  'package.json' and 'pnpm-lock.yaml', but I am still getting "failed to run npm ci".
@cerashdan @maramesk

**Comment by maramesk** [comment]
@yomnak Looks like there are missing dependencies which ur trying to use but are not installed. try installing the libraries from your project dir and rerun
```
npm install @fortawesome/fontawesome-free@6.5.2
npm install react-icons@5.1.0
```

**Comment by maramesk** [comment]
Also pnpm is different than npm, Rashdan asked you to update your npm so make sure you do so:
 `npm install -g npm@latest
`

**Comment by yomnak** [comment]
I've installed the missing dependences and it worked. thank you 🙏
